# Proc Chance
SHOOTING_STAR_PROC_CHANCE = 0.15
UMBRAL_EMBRACE_PROC_CHANCE = 0.015
POWER_OF_GOLDRINN_PROC_CHANCE = 0.33
DENIZENS_PROC_CHANCE = 0.005
STARWEAVERS_WEFT = .2
STARWEAVERS_WARP = .4

# Damage Buffs
TWIN_MOONS_BUFF = .1
UMBRAL_INTENSITY_WRATH = 0.1
RTS_DAMAGE_BUFF = 0.1
RTS_AP_REDUC = 0.05
BASE_BOAT_CRIT_BUFF = 8
MOONKIN_DAMAGE_BUFF = .1
LYCARAS_MASTERY_BUFF = 5.4
ECLIPSE_WRATH_BUFF = .2
ECLIPSE_NATURE_BUFF = .15
ECLIPSE_ARCANE_BUFF = .15
NATURES_GRACE_HASTE_BUFF = 0.15
UMBRAL_EMBRACE_DAMAGE_BUFF = 0.25
CELESTIAL_ALIGNMENT_HASTE_BUFF = 0.2
INCARNATION_CRIT_BUFF = 0.1

# Buff Timers
SOLSTICE_BUFF_TIME = 6
NATURES_GRACE_BUFF_TIME = 6
STARLORD_BUFF_TIME = 15
AETHERIAL_KINDLING_EXTEND = 4
AETHERIAL_KINDLING_MAX = 28
BOAT_DECAY = 1
ASTRAL_SMOLDER_TIMER = 4
UMBRAL_EMBRACE_BUFF_TIME = 15
STARWEAVERS_BUFF_TIME = 30
CELESTIAL_ALIGNMENT_BUFF_TIME = 20
INCARNATION_BUFF_TIME = 30
RATTLE_THE_STARS_BUFF_TIME = 5

# Misc
RADIANT_MOONLIGHT_FOE = 15
SOUL_OF_THE_FOREST_WRATH = 0.5
MAX_RATTLE_THE_STARS = 2
MAX_STARLORD_STACKS = 3
STARLORD_HASTE = 0.02
PULSAR_MAX = 600
ELUNES_GUIDANCE_STARSURGE = 5
ELUNES_GUIDANCE_STARFALL = 8
SUNDERED_FIRMAMENT_EFFECTIVENESS = 0.2